require: rubocop-rails
AllCops:
  Exclude:
    - 'bin/**/*'
    - config/application.rb
    - 'db/(*_)?schema.rb'
    - 'Gemfile'
    - 'node_modules/**/*'
  NewCops: enable
  TargetRubyVersion: 3.0.0
Layout/HashAlignment:
  EnforcedColonStyle: table
Naming/VariableNumber:
  EnforcedStyle: snake_case
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/MixinGrouping:
  EnforcedStyle: grouped
