require: rubocop-rails
AllCops:
  Exclude:
    - bin/**/*
    - config/application.rb
    - !ruby/regexp  /db\/.*schema.rb$/
    - db/migrate/*
    - Gemfile
    - node_modules/**/*
    - test/**/*
    - test/models/comment_test.rb
    - storage/**/*
    - tmp/**/*
  NewCops: enable
  TargetRubyVersion: 3.0.0
Layout/HashAlignment:
  EnforcedColonStyle: table
Naming/VariableNumber:
  EnforcedStyle: snake_case
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/MixinGrouping:
  EnforcedStyle: grouped
